$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$reportPath = Join-Path $root 'src\Functions\ZZZZZZZZZZ-ReportTwoPage.ps1'
$source = Get-Content -LiteralPath $reportPath -Raw -Encoding UTF8

# The redundant Result summary previously collided with the fixed footer on page 2.
if ($source -match '<h2>\s*Result\s*</h2>') {
    throw 'The redundant Result summary must not be printed on page 2.'
}

# Preserve two-page output, benchmark/QC details, explicit failure reasons,
# evidence hashes, and the fixed footer.
if ([regex]::Matches($source, '<div class="sheet">').Count -ne 2) {
    throw 'The QC certificate must retain exactly two report sheets.'
}
foreach ($required in @(
    '<h2>Performance Qualification</h2>',
    '<h2>Full System Burn-In</h2>',
    '<h2>$checkTitle</h2>',
    '$exactFailureSection',
    'Hardware Identity SHA-256',
    'Manifest SHA-256',
    'Generated by SITEC PC Assembly &amp; QC'
)) {
    if (-not $source.Contains($required)) {
        throw "Missing required QC certificate content: $required"
    }
}

Write-Host 'QC certificate page-two summary regression test passed.' -ForegroundColor Green
