<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>SitecQC</AssemblyName>
    <RootNamespace>SitecQC.Launcher</RootNamespace>
    <Version>3.1.0</Version>
    <FileVersion>3.1.0.0</FileVersion>
    <AssemblyVersion>3.1.0.0</AssemblyVersion>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="payload.zip" Condition="Exists('payload.zip')" LogicalName="SitecQC.Payload.zip" />
  </ItemGroup>
</Project>
